// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rssnews.Services;

#nullable disable

namespace rssnews.Migrations
{
    [DbContext(typeof(RSSNewsDbContext))]
    partial class RSSNewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rssnews.Models.Author", b =>
                {
                    b.Property<string>("AuthorID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AuthorID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.HasKey("AuthorID")
                        .HasName("PK_Author");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Author_Name");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("rssnews.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CategoryName");

                    b.HasKey("CategoryID")
                        .HasName("PK_Category");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_CategoryName");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("rssnews.Models.Item", b =>
                {
                    b.Property<string>("ItemID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ItemID");

                    b.Property<string>("AuthorID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AuthorID");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Link");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Title");

                    b.HasKey("ItemID")
                        .HasName("PK_Item");

                    b.HasIndex("AuthorID")
                        .HasDatabaseName("IX_Item_AuthorID");

                    b.HasIndex("CategoryID")
                        .HasDatabaseName("IX_Item_CategoryID");

                    b.HasIndex("PublishedDate")
                        .HasDatabaseName("IX_Item_PublishedDate");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("rssnews.Models.Item", b =>
                {
                    b.HasOne("rssnews.Models.Author", "Author")
                        .WithMany("Items")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Item_Author");

                    b.HasOne("rssnews.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Item_Category");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("rssnews.Models.Author", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("rssnews.Models.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
