// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rssnews.Services;

#nullable disable

namespace rssnews.Migrations
{
    [DbContext(typeof(RSSNewsDbContext))]
    partial class RSSNewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rssnews.Models.Author", b =>
                {
                    b.Property<string>("AuthorID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AuthorID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.HasKey("AuthorID")
                        .HasName("PK_Author");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("rssnews.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.HasKey("CategoryID")
                        .HasName("PK_Category");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("rssnews.Models.Item", b =>
                {
                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ItemID");

                    b.Property<string>("AuthorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AuthorID");

                    b.Property<string>("AuthorID1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("CategoryID1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Link");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Published_Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("ItemID")
                        .HasName("PK_Item");

                    b.HasIndex("AuthorID");

                    b.HasIndex("AuthorID1");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CategoryID1");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("rssnews.Models.Item", b =>
                {
                    b.HasOne("rssnews.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Author");

                    b.HasOne("rssnews.Models.Author", null)
                        .WithMany("Items")
                        .HasForeignKey("AuthorID1");

                    b.HasOne("rssnews.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Category");

                    b.HasOne("rssnews.Models.Category", null)
                        .WithMany("Items")
                        .HasForeignKey("CategoryID1");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("rssnews.Models.Author", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("rssnews.Models.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
