// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "rss.proto" (package "rssfeed", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RSSItemService } from "./rss";
import type { DeleteRSSItemResponse } from "./rss";
import type { DeleteRSSItemRequest } from "./rss";
import type { UpdateRSSItemRequest } from "./rss";
import type { GetRSSItemsRequest } from "./rss";
import type { GetRSSItemResponse } from "./rss";
import type { Empty } from "./google/protobuf/empty";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Item } from "./rss";
import type { AddRSSItemRequest } from "./rss";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service rssfeed.RSSItemService
 */
export interface IRSSItemServiceClient {
    /**
     * @generated from protobuf rpc: AddRSSItem
     */
    addRSSItem(input: AddRSSItemRequest, options?: RpcOptions): UnaryCall<AddRSSItemRequest, Item>;
    /**
     * @generated from protobuf rpc: GetRSSItems
     */
    getRSSItems(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetRSSItemResponse>;
    /**
     * @generated from protobuf rpc: GetRSSItemByID
     */
    getRSSItemByID(input: GetRSSItemsRequest, options?: RpcOptions): UnaryCall<GetRSSItemsRequest, Item>;
    /**
     * @generated from protobuf rpc: UpdateRSSItem
     */
    updateRSSItem(input: UpdateRSSItemRequest, options?: RpcOptions): UnaryCall<UpdateRSSItemRequest, Item>;
    /**
     * @generated from protobuf rpc: DeleteRSSItem
     */
    deleteRSSItem(input: DeleteRSSItemRequest, options?: RpcOptions): UnaryCall<DeleteRSSItemRequest, DeleteRSSItemResponse>;
}
/**
 * @generated from protobuf service rssfeed.RSSItemService
 */
export class RSSItemServiceClient implements IRSSItemServiceClient, ServiceInfo {
    typeName = RSSItemService.typeName;
    methods = RSSItemService.methods;
    options = RSSItemService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddRSSItem
     */
    addRSSItem(input: AddRSSItemRequest, options?: RpcOptions): UnaryCall<AddRSSItemRequest, Item> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRSSItemRequest, Item>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRSSItems
     */
    getRSSItems(input: Empty, options?: RpcOptions): UnaryCall<Empty, GetRSSItemResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GetRSSItemResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRSSItemByID
     */
    getRSSItemByID(input: GetRSSItemsRequest, options?: RpcOptions): UnaryCall<GetRSSItemsRequest, Item> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRSSItemsRequest, Item>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRSSItem
     */
    updateRSSItem(input: UpdateRSSItemRequest, options?: RpcOptions): UnaryCall<UpdateRSSItemRequest, Item> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRSSItemRequest, Item>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteRSSItem
     */
    deleteRSSItem(input: DeleteRSSItemRequest, options?: RpcOptions): UnaryCall<DeleteRSSItemRequest, DeleteRSSItemResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRSSItemRequest, DeleteRSSItemResponse>("unary", this._transport, method, opt, input);
    }
}
