// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "rss.proto" (package "rssfeed", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message rssfeed.Item
 */
export interface Item {
    /**
     * @generated from protobuf field: string item_id = 1
     */
    itemId: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string link = 3
     */
    link: string;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_date = 5
     */
    publishedDate?: Timestamp;
    /**
     * @generated from protobuf field: rssfeed.Category category = 6
     */
    category?: Category;
    /**
     * @generated from protobuf field: rssfeed.Author author = 7
     */
    author?: Author;
}
/**
 * @generated from protobuf message rssfeed.Category
 */
export interface Category {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
}
/**
 * @generated from protobuf message rssfeed.Author
 */
export interface Author {
    /**
     * @generated from protobuf field: string author_id = 1
     */
    authorId: string;
    /**
     * @generated from protobuf field: string firstname = 2
     */
    firstname: string;
    /**
     * @generated from protobuf field: string lastname = 3
     */
    lastname: string;
}
/**
 * @generated from protobuf message rssfeed.AddRSSItemRequest
 */
export interface AddRSSItemRequest {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string link = 2
     */
    link: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_date = 4
     */
    publishedDate?: Timestamp;
    /**
     * @generated from protobuf field: rssfeed.Category category = 5
     */
    category?: Category;
    /**
     * @generated from protobuf field: rssfeed.Author author = 6
     */
    author?: Author;
}
/**
 * @generated from protobuf message rssfeed.GetRSSItemsRequest
 */
export interface GetRSSItemsRequest {
    /**
     * @generated from protobuf field: string item_id = 1
     */
    itemId: string;
}
/**
 * @generated from protobuf message rssfeed.GetRSSItemResponse
 */
export interface GetRSSItemResponse {
    /**
     * @generated from protobuf field: repeated rssfeed.Item items = 1
     */
    items: Item[];
}
/**
 * @generated from protobuf message rssfeed.UpdateRSSItemRequest
 */
export interface UpdateRSSItemRequest {
    /**
     * @generated from protobuf field: string item_id = 1
     */
    itemId: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string link = 3
     */
    link: string;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_date = 5
     */
    publishedDate?: Timestamp;
    /**
     * @generated from protobuf field: rssfeed.Category category = 6
     */
    category?: Category;
    /**
     * @generated from protobuf field: rssfeed.Author author = 7
     */
    author?: Author;
}
/**
 * @generated from protobuf message rssfeed.DeleteRSSItemRequest
 */
export interface DeleteRSSItemRequest {
    /**
     * @generated from protobuf field: string item_id = 1
     */
    itemId: string;
}
/**
 * @generated from protobuf message rssfeed.DeleteRSSItemResponse
 */
export interface DeleteRSSItemResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Item$Type extends MessageType<Item> {
    constructor() {
        super("rssfeed.Item", [
            { no: 1, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "link", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "published_date", kind: "message", T: () => Timestamp },
            { no: 6, name: "category", kind: "message", T: () => Category },
            { no: 7, name: "author", kind: "message", T: () => Author }
        ]);
    }
    create(value?: PartialMessage<Item>): Item {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemId = "";
        message.title = "";
        message.link = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<Item>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Item): Item {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string item_id */ 1:
                    message.itemId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string link */ 3:
                    message.link = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_date */ 5:
                    message.publishedDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedDate);
                    break;
                case /* rssfeed.Category category */ 6:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                case /* rssfeed.Author author */ 7:
                    message.author = Author.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Item, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string item_id = 1; */
        if (message.itemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.itemId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string link = 3; */
        if (message.link !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.link);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* google.protobuf.Timestamp published_date = 5; */
        if (message.publishedDate)
            Timestamp.internalBinaryWrite(message.publishedDate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Category category = 6; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Author author = 7; */
        if (message.author)
            Author.internalBinaryWrite(message.author, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.Item
 */
export const Item = new Item$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Category$Type extends MessageType<Category> {
    constructor() {
        super("rssfeed.Category", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Category>): Category {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<Category>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Category): Category {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Category, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.Category
 */
export const Category = new Category$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Author$Type extends MessageType<Author> {
    constructor() {
        super("rssfeed.Author", [
            { no: 1, name: "author_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "firstname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "lastname", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Author>): Author {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.authorId = "";
        message.firstname = "";
        message.lastname = "";
        if (value !== undefined)
            reflectionMergePartial<Author>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Author): Author {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string author_id */ 1:
                    message.authorId = reader.string();
                    break;
                case /* string firstname */ 2:
                    message.firstname = reader.string();
                    break;
                case /* string lastname */ 3:
                    message.lastname = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Author, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string author_id = 1; */
        if (message.authorId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.authorId);
        /* string firstname = 2; */
        if (message.firstname !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.firstname);
        /* string lastname = 3; */
        if (message.lastname !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.lastname);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.Author
 */
export const Author = new Author$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddRSSItemRequest$Type extends MessageType<AddRSSItemRequest> {
    constructor() {
        super("rssfeed.AddRSSItemRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "link", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "published_date", kind: "message", T: () => Timestamp },
            { no: 5, name: "category", kind: "message", T: () => Category },
            { no: 6, name: "author", kind: "message", T: () => Author }
        ]);
    }
    create(value?: PartialMessage<AddRSSItemRequest>): AddRSSItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.link = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<AddRSSItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddRSSItemRequest): AddRSSItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string link */ 2:
                    message.link = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_date */ 4:
                    message.publishedDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedDate);
                    break;
                case /* rssfeed.Category category */ 5:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                case /* rssfeed.Author author */ 6:
                    message.author = Author.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddRSSItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string link = 2; */
        if (message.link !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.link);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* google.protobuf.Timestamp published_date = 4; */
        if (message.publishedDate)
            Timestamp.internalBinaryWrite(message.publishedDate, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Category category = 5; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Author author = 6; */
        if (message.author)
            Author.internalBinaryWrite(message.author, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.AddRSSItemRequest
 */
export const AddRSSItemRequest = new AddRSSItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRSSItemsRequest$Type extends MessageType<GetRSSItemsRequest> {
    constructor() {
        super("rssfeed.GetRSSItemsRequest", [
            { no: 1, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRSSItemsRequest>): GetRSSItemsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemId = "";
        if (value !== undefined)
            reflectionMergePartial<GetRSSItemsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRSSItemsRequest): GetRSSItemsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string item_id */ 1:
                    message.itemId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRSSItemsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string item_id = 1; */
        if (message.itemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.itemId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.GetRSSItemsRequest
 */
export const GetRSSItemsRequest = new GetRSSItemsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRSSItemResponse$Type extends MessageType<GetRSSItemResponse> {
    constructor() {
        super("rssfeed.GetRSSItemResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Item }
        ]);
    }
    create(value?: PartialMessage<GetRSSItemResponse>): GetRSSItemResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<GetRSSItemResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRSSItemResponse): GetRSSItemResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated rssfeed.Item items */ 1:
                    message.items.push(Item.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRSSItemResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated rssfeed.Item items = 1; */
        for (let i = 0; i < message.items.length; i++)
            Item.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.GetRSSItemResponse
 */
export const GetRSSItemResponse = new GetRSSItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateRSSItemRequest$Type extends MessageType<UpdateRSSItemRequest> {
    constructor() {
        super("rssfeed.UpdateRSSItemRequest", [
            { no: 1, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "link", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "published_date", kind: "message", T: () => Timestamp },
            { no: 6, name: "category", kind: "message", T: () => Category },
            { no: 7, name: "author", kind: "message", T: () => Author }
        ]);
    }
    create(value?: PartialMessage<UpdateRSSItemRequest>): UpdateRSSItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemId = "";
        message.title = "";
        message.link = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateRSSItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateRSSItemRequest): UpdateRSSItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string item_id */ 1:
                    message.itemId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string link */ 3:
                    message.link = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_date */ 5:
                    message.publishedDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedDate);
                    break;
                case /* rssfeed.Category category */ 6:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                case /* rssfeed.Author author */ 7:
                    message.author = Author.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateRSSItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string item_id = 1; */
        if (message.itemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.itemId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string link = 3; */
        if (message.link !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.link);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* google.protobuf.Timestamp published_date = 5; */
        if (message.publishedDate)
            Timestamp.internalBinaryWrite(message.publishedDate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Category category = 6; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* rssfeed.Author author = 7; */
        if (message.author)
            Author.internalBinaryWrite(message.author, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.UpdateRSSItemRequest
 */
export const UpdateRSSItemRequest = new UpdateRSSItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteRSSItemRequest$Type extends MessageType<DeleteRSSItemRequest> {
    constructor() {
        super("rssfeed.DeleteRSSItemRequest", [
            { no: 1, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteRSSItemRequest>): DeleteRSSItemRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.itemId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteRSSItemRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteRSSItemRequest): DeleteRSSItemRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string item_id */ 1:
                    message.itemId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteRSSItemRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string item_id = 1; */
        if (message.itemId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.itemId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.DeleteRSSItemRequest
 */
export const DeleteRSSItemRequest = new DeleteRSSItemRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteRSSItemResponse$Type extends MessageType<DeleteRSSItemResponse> {
    constructor() {
        super("rssfeed.DeleteRSSItemResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteRSSItemResponse>): DeleteRSSItemResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteRSSItemResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteRSSItemResponse): DeleteRSSItemResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteRSSItemResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message rssfeed.DeleteRSSItemResponse
 */
export const DeleteRSSItemResponse = new DeleteRSSItemResponse$Type();
/**
 * @generated ServiceType for protobuf service rssfeed.RSSItemService
 */
export const RSSItemService = new ServiceType("rssfeed.RSSItemService", [
    { name: "AddRSSItem", options: {}, I: AddRSSItemRequest, O: Item },
    { name: "GetRSSItems", options: {}, I: Empty, O: GetRSSItemResponse },
    { name: "GetRSSItemByID", options: {}, I: GetRSSItemsRequest, O: Item },
    { name: "UpdateRSSItem", options: {}, I: UpdateRSSItemRequest, O: Item },
    { name: "DeleteRSSItem", options: {}, I: DeleteRSSItemRequest, O: DeleteRSSItemResponse }
]);
